[request_definition]
r = sub, obj, act

[policy_definition]
p = sub_role, obj_type, act, eft

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow)) && !some(where (p.eft == deny))

[matchers]
m = g(r.sub.role, p.sub_role) && (keyMatch(r.obj.type, p.obj_type) || (r.obj.is_readonly && p.obj_type == "readonly_room")) && keyMatch(r.act, p.act)
